parameters:
  - name: codeScanFileName
    type: string
  - name: uploadPath
    type: string

  - name: codeScanContainerName
    type: string
    default: "codeScan"

steps:
  - template: docker-template.yml
    parameters:
      dockerConfigName: "commonDockerConfig"
      repoName: "code-scan"
      repoTag: "1.0"
      dockerFileName: "DockerfileCodeScan"
      containerName: ${{ parameters.codeScanContainerName }}

  - script: |
      docker exec ${{ parameters.codeScanContainerName }} bash /neural-compressor/.azure-pipelines/scripts/codeScan/${{ parameters.codeScanFileName }}/${{ parameters.codeScanFileName }}.sh
    displayName: "${{ parameters.codeScanFileName }} Check"

  - task: PublishPipelineArtifact@1
    condition: succeededOrFailed()
    inputs:
      targetPath: .azure-pipelines/scripts/codeScan/scanLog/${{ parameters.uploadPath }}
      artifact: ${{ parameters.codeScanFileName }}
      publishLocation: "pipeline"
    displayName: "PublishPipelineArtifact"

  - task: Bash@3
    condition: always()
    inputs:
      targetType: "inline"
      script: |
        docker exec ${{ parameters.codeScanContainerName }} bash -c "rm -fr /neural-compressor/* && rm -fr /neural-compressor/.* || true"
    displayName: "Docker clean up"
