trigger: none

pr:
  autoCancel: true
  drafts: false
  branches:
    include:
    - master
  paths:
    include:
    - neural_coder
    - test/neural_coder
    - setup.py

pool: ICX-16C

variables:
  UPLOAD_PATH: $(Build.SourcesDirectory)/log_dir

stages:
- stage:
  displayName: Unit Test for Neural Coder
  jobs:
  - job:
    steps:
      - template: template/ut-template.yml
        parameters:
          dockerConfigName: 'commonDockerConfig'
          utScriptFileName: 'run_ncoder'
          uploadPath: $(UPLOAD_PATH)
          utArtifact: 'ut-ncoder'
          utContainerName: "utTest-ncoder"
